### ISSUE TITLE
GitPitch.com is shutting down. This slide deck will no longer be available from March 1, 2021.

### ISSUE THREAD

**Issue by dglaude** [robmarkcole/circuitpython-on-home-assistant#1]
Warning, you may want to move your presentation somewhere else.
I got the title message when clicking on the link for your presentation:

Presentation on circuitpython at https://gitpitch.com/robmarkcole/circuitpython-on-home-assistant/master

**Comment by robmarkcole** [comment]
thanks for the heads up, addressed
